<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotnetAgents.Runtime\DotnetAgents.Runtime.csproj" />
    <ProjectReference Include="..\..\src\DotnetAgents.Tools.BuiltIn\DotnetAgents.Tools.BuiltIn.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
